require('001_core')
require('002_keymap')
require('003_colorscheme')

require('plugins')
require('plugins/101-lualine')
require('plugins/102-bufferline')
require('plugins/103-telescope')
require('plugins/104-nvimtree')
require('plugins/105-lspconfig')